---
# yaml-language-server: $schema=https://schema.miquido.dev

ignored_metrics:
  - static_analysis
  - unit_tests
  - test_coverage
  - container_vulnerabilities
  - dependencies_vulnerabilities
  - integration_tests
